"use client";

import Link from "next/link";
import { Plus, TrendingUp } from "lucide-react";
import { useAppContext } from "@/components/app-context";
import { Badge, Card, EmptyState, SectionHeader } from "@/components/ui";
import { formatMetric } from "@/lib/analytics";

export default function CompetitorsPage() {
  const { brandId, brands, competitors } = useAppContext();
  const brand = brands.find((item) => item.id === brandId);
  const rows = competitors.filter((item) => item.brandId === brandId);

  return <div className="space-y-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><Badge tone="neutral">Public data only</Badge><h1 className="page-title mt-4">Competitor intelligence</h1><p className="page-subtitle">Public channel and video signals for {brand?.name ?? "the selected brand"}. Private retention, search terms, traffic sources and audience analytics are never implied.</p></div><Link href={`/onboarding?brand=${brandId}`} className="inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-[var(--accent)] px-4 text-sm font-semibold text-white"><Plus size={16} /> Add competitor</Link></div>
    {rows.length === 0 ? <EmptyState title="No competitors configured" description="Add a public YouTube channel in workspace setup. Metrics remain pending until a public-data sync runs." /> : <>
      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{rows.map((item) => { const hasSnapshot = item.subscribers !== undefined; return <Card key={item.id} className="p-5"><div className="flex items-start justify-between"><div className="grid size-10 place-items-center rounded-xl bg-slate-900 text-xs font-bold text-white">{item.name.split(" ").map((word) => word[0]).join("").slice(0, 2)}</div><Badge tone={hasSnapshot ? "accent" : "warning"}>{hasSnapshot ? <><TrendingUp size={12} /> Demo snapshot</> : "Sync pending"}</Badge></div><p className="mt-4 font-semibold">{item.name}</p><p className="mt-1 text-xs text-[var(--muted)]">{item.channelUrl ?? "Cached public demonstration data"}</p><div className="mt-5 grid grid-cols-2 gap-3"><div><p className="text-xs text-[var(--muted)]">Subscribers</p><p className="mt-1 font-bold">{hasSnapshot ? formatMetric(item.subscribers ?? 0) : "—"}</p></div><div><p className="text-xs text-[var(--muted)]">Median views</p><p className="mt-1 font-bold">{hasSnapshot ? formatMetric(item.medianViews ?? 0) : "—"}</p></div><div><p className="text-xs text-[var(--muted)]">Recent uploads</p><p className="mt-1 font-bold">{item.recentUploads ?? "—"}</p></div><div><p className="text-xs text-[var(--muted)]">Shorts share</p><p className="mt-1 font-bold">{item.shortsShare === undefined ? "—" : `${Math.round(item.shortsShare * 100)}%`}</p></div></div>{item.breakoutTitle && <div className="mt-5 rounded-xl bg-[var(--surface)] p-3"><p className="text-[10px] font-bold uppercase tracking-wide text-[var(--muted)]">Breakout title</p><p className="mt-1 text-sm font-medium leading-5">{item.breakoutTitle}</p></div>}</Card>; })}</div>
      <Card className="overflow-hidden"><div className="p-5"><SectionHeader title="Public comparison" description="Recent upload behavior and public viewing baselines. Demo snapshots are labeled and manual entries wait for sync." /></div><div className="overflow-x-auto"><table className="w-full min-w-[740px] text-left text-sm"><thead className="bg-[var(--surface)] text-xs uppercase tracking-wide text-[var(--muted)]"><tr><th className="px-5 py-3">Channel</th><th className="px-5 py-3">Subscribers</th><th className="px-5 py-3">Recent uploads</th><th className="px-5 py-3">Median views</th><th className="px-5 py-3">Shorts share</th><th className="px-5 py-3">Source</th></tr></thead><tbody className="divide-y divide-[var(--border)]">{rows.map((item) => <tr key={item.id}><td className="px-5 py-4 font-semibold">{item.name}</td><td className="px-5 py-4">{item.subscribers === undefined ? "—" : formatMetric(item.subscribers)}</td><td className="px-5 py-4">{item.recentUploads ?? "—"}</td><td className="px-5 py-4">{item.medianViews === undefined ? "—" : formatMetric(item.medianViews)}</td><td className="px-5 py-4">{item.shortsShare === undefined ? "—" : `${Math.round(item.shortsShare * 100)}%`}</td><td className="px-5 py-4 text-[var(--muted)]">{item.source === "demo" ? "Demo" : "Manual"}</td></tr>)}</tbody></table></div></Card>
    </>}
  </div>;
}
